import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const checks=[];
const add=(name,ok,detail='')=>checks.push({name,ok,detail});
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('index.html');
const robots=read('public/robots.txt');
const llms=read('public/llms.txt');
const meta=read('src/extra-features.jsx');
const main=read('src/main.jsx');
add('Homepage title targets JIIT Youth Club + clubs/events/fests',html.includes('JIIT Youth Club 128') && main.includes('Clubs, Events & Fests'));
add('Organization structured data',meta.includes("'@type':'Organization'") && meta.includes('sameAs') && meta.includes('areaServed') && meta.includes('contactPoint'));
add('Club collection structured data',meta.includes("'@type':'CollectionPage'")&&meta.includes('ItemList')&&meta.includes('JYC Clubs & Communities'));
add('Gallery collection structured data',meta.includes("'@type':'CollectionPage'")&&meta.includes('JYC Visual Archive'));
add('Event schema uses source images and full campus address',meta.includes('sourceEventMedia(item)')&&meta.includes('streetAddress')&&meta.includes('Sector 128, Wish Town Campus'));
add('Event structured data',meta.includes("'@type':'Event'") && meta.includes('startDate'));
add('Breadcrumb structured data',meta.includes("'@type':'BreadcrumbList'") && meta.includes('itemListElement'));
add('Dynamic canonical URLs',meta.includes('canonical') && meta.includes('VITE_SITE_URL') && meta.includes('jiityouthclub128.in'));
add('Open Graph image',meta.includes("og:image") && meta.includes("og:image:alt") && html.includes('og:image'));
add('Private route noindex',main.includes("clean.startsWith('/qr/')") && meta.includes("noindex,nofollow"));
add('Robots allows public crawling',robots.includes('Allow: /') && robots.includes('Disallow: /admin'));
add('Robots publishes canonical sitemap',robots.includes('Sitemap: https://www.jiityouthclub128.in/sitemap.xml'));
add('Sitemap generator includes maintained source hubs',fs.readFileSync(path.join(root,'scripts/generate-sitemap.mjs'),'utf8').includes('jyc-hub-registry.js')&&fs.readFileSync(path.join(root,'scripts/generate-sitemap.mjs'),'utf8').includes('/clubs/${slug(name)}'));
add('Sitemap carries maintained hub photography',fs.readFileSync(path.join(root,'scripts/generate-sitemap.mjs'),'utf8').includes('slugToHubImages')&&fs.readFileSync(path.join(root,'scripts/generate-sitemap.mjs'),'utf8').includes('xmlns:image'));
add('LLMs discovery file',llms.includes('JIIT Youth Club') && llms.includes('/clubs') && llms.includes('/events'));
add('Flagship event URLs are seeded into sitemap',fs.readFileSync(path.join(root,'scripts/generate-sitemap.mjs'),'utf8').includes('/events/agentic-ai-2026')&&fs.readFileSync(path.join(root,'scripts/generate-sitemap.mjs'),'utf8').includes('/events/ride-hack-2026')&&fs.readFileSync(path.join(root,'scripts/generate-sitemap.mjs'),'utf8').includes('/events/converge-2026')&&fs.readFileSync(path.join(root,'scripts/generate-sitemap.mjs'),'utf8').includes('/events/drono-o-war-2026')&&fs.readFileSync(path.join(root,'scripts/generate-sitemap.mjs'),'utf8').includes('/events/codeai-hackathon'));
add('Sitemap generator exists',fs.existsSync(path.join(root,'scripts/generate-sitemap.mjs')));
add('SEO pages have useful route metadata',main.includes('JIIT Clubs & Student Communities') && main.includes('JIIT Events & Campus Activities') && main.includes('About JIIT Youth Club') && main.includes('JIIT Fests & Flagship Events'));
add('Fest discovery route exists',main.includes("clean==='/fests'") && llms.includes('/fests'));
add('Search-intent editorial content is visible on key pages',main.includes('SearchTopicBand') && main.includes('Official JIIT clubs and student communities') && main.includes('JIIT events, workshops and campus experiences'));
add('Service worker cache namespace matches current release',read('public/sw.js').includes('jyc-cache-v56-5-0'));
const failed=checks.filter(x=>!x.ok);
for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'}: ${c.name}${c.detail?` — ${c.detail}`:''}`);
if(failed.length){process.exitCode=1;console.error(`SEO QA failed: ${failed.length} check(s)`)} else console.log(`PASS: SEO QA (${checks.length} checks)`);
