import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const main=fs.readFileSync(path.join(root,'src','main.jsx'),'utf8');
const extra=fs.readFileSync(path.join(root,'src','extra-features.jsx'),'utf8');
const admin=fs.readFileSync(path.join(root,'src','admin-chunk.jsx'),'utf8');
const css=fs.readFileSync(path.join(root,'src','v18.10-best-pass.css'),'utf8');
const config=fs.readFileSync(path.join(root,'src','lib','site-config.js'),'utf8');
const fail=[];
const expect=(ok,msg)=>{if(!ok)fail.push(msg)};
for(const name of ['Team','ClubDetail','JYCAssistant','ShareButton','DetailSection','NavIcon'])expect(new RegExp('(function|const)\\s+'+name+'\\b').test(main),`main missing ${name}`);
expect(/GalleryItems}/.test(main)&&/export function GalleryItems/.test(extra),'GalleryItems runtime contract missing');
for(const name of ['ManageAdmins','ManageCalendarSettings','ManageCategories','ManageFest','ManageGallery','ManageHomepage','ManageNotifications','ManagePlatform','ManageTeam'])expect(new RegExp(`function\\s+${name}\\b`).test(admin),`admin missing ${name}`);
expect(/export function Gallery\(/.test(extra),'Gallery is not exported');
expect(/export function GalleryItems\(/.test(extra),'GalleryItems is not exported');
expect(/Gallery,GalleryItems/.test(main),'main does not import Gallery + GalleryItems');
expect(/jyc-custom-cursor/.test(css),'cursor polish missing');
expect(/bird-trio-grid/.test(css),'Phoenix trio polish missing');
expect(/calendar-mode-tabs/.test(css),'calendar polish missing');
expect(/exact title/i.test(fs.readFileSync(path.join(root,'src/lib/search.js'),'utf8')),'search priority implementation missing');
expect(/relevanceScore/.test(fs.readFileSync(path.join(root,'src/lib/search.js'),'utf8')),'search scoring missing');
expect(/JYC_CONTACTS/.test(config)&&/CREATOR/.test(config),'site contact/creator config is not centralized');
expect(!/chat\.whatsapp\.com|instagram\.com\/jiityouthclub128/.test(fs.readFileSync(path.join(root,'src','main.jsx'),'utf8').replace(/import[^\n]+/g,'')),'main contains duplicated hardcoded JYC social URLs');
if(fail.length){console.error(fail.map(x=>`FAIL: ${x}`).join('\n'));process.exit(1)}
console.log('V18.11 best-of-previous releases QA complete.');
console.log('- Team, club detail, gallery, assistant and share runtime contracts present.');
console.log('- Admin management workspaces restored.');
console.log('- Phoenix trio, cursor, calendar and responsive polish present.');
console.log('- Search relevance contract present.');
