import React,{useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';

const savedKeys={club:'jyc-saved-club-',event:'jyc-saved-event-'};
const slug=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const publishedEvents=data=>data.events.filter(e=>e.published&&!e.archived);
const publishedClubs=data=>data.clubs.filter(c=>c.published&&c.status!=='archived');
const eventState=e=>{const start=new Date(`${e.date}T${e.start||'00:00'}`).getTime();const end=new Date(`${e.date}T${e.end||'23:59'}`).getTime();const now=Date.now();if(!e.date)return 'draft';if(now<start)return 'upcoming';if(now<=end)return 'live';return 'past'};
const fmtDate=s=>s?new Date(`${s}T12:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'Date TBA';

export function usePageMeta(title,description,path=''){useEffect(()=>{const full=title?`${title} · JIIT Youth Club`:'JIIT Youth Club · Ready to Soar';document.title=full;const set=(name,content,attr='name')=>{let el=document.head.querySelector(`meta[${attr}="${name}"]`);if(!el){el=document.createElement('meta');el.setAttribute(attr,name);document.head.appendChild(el)}el.setAttribute('content',content||'')};set('description',description||'Official JIIT Youth Club, Sector 128, Noida. Discover clubs, events, fests and campus experiences.');set('og:title',full,'property');set('og:description',description||'Official JIIT Youth Club, Sector 128, Noida.','property');set('og:type','website','property');set('og:url',window.location.href,'property');set('twitter:card','summary_large_image');set('twitter:title',full);set('twitter:description',description||'Official JIIT Youth Club, Sector 128, Noida.');if(path){let canonical=document.head.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=`${window.location.origin}${path}`}},[title,description,path])}

export function SkipLink(){return <a className="skip-link" href="#main-content">Skip to content</a>}

export function MaintenanceGate({data,children}){const enabled=Boolean(data?.maintenance?.on);if(!enabled)return children;return <section className="maintenance-page"><div className="maintenance-orbit"/><span className="eyebrow">JYC · MAINTENANCE MODE</span><h1>{data.maintenance.title||'JYC is getting ready.'}</h1><p>{data.maintenance.message||"We’re making a few improvements. Please check back shortly."}</p><small>Control Center remains available to authorized administrators.</small></section>}

export function InstallPrompt(){const [prompt,setPrompt]=useState(null);useEffect(()=>{const fn=e=>{e.preventDefault();setPrompt(e)};window.addEventListener('beforeinstallprompt',fn);return()=>window.removeEventListener('beforeinstallprompt',fn)},[]);if(!prompt)return null;return <div className="install-prompt"><div><strong>Install JYC</strong><span>Keep JYC one tap away on your phone or desktop.</span></div><button onClick={async()=>{await prompt.prompt();setPrompt(null)}}>Install</button><button className="ghost" onClick={()=>setPrompt(null)}>×</button></div>}

export function ThisWeek({data}){const nav=useNavigate();const today=new Date();today.setHours(0,0,0,0);const end=new Date(today);end.setDate(end.getDate()+7);const events=publishedEvents(data).filter(e=>{const d=new Date(`${e.date}T12:00`);return d>=today&&d<end}).sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`));return <section className="section week-section"><div className="feature-banner"><div><span className="eyebrow">THIS WEEK</span><h2>What’s happening around JYC.</h2><p>Published events are collected automatically for the next seven days.</p></div><button className="text-link" onClick={()=>nav('/calendar')}>Open calendar →</button></div>{events.length?<div className="week-list">{events.map(e=><button key={e.id} onClick={()=>nav('/events/'+e.id)}><span>{fmtDate(e.date)}</span><strong>{e.title}</strong><small>{e.start||'Time TBA'} · {e.venue||'Venue TBA'}</small>{eventState(e)==='live'&&<em>LIVE</em>}</button>)}</div>:<div className="feature-empty"><strong>Nothing scheduled yet.</strong><span>When JYC publishes an event for the week, it will appear here automatically.</span></div>}</section>}

function HubCard({title,text,count,onClick,label}){return <button className="hub-card" onClick={onClick}><span className="eyebrow">{label}</span><strong>{title}</strong><p>{text}</p><small>{count} currently available · Explore →</small></button>}
export function RecruitmentHub({data}){const nav=useNavigate();const clubs=publishedClubs(data).filter(c=>c.recruitment?.on);return <section className="section page feature-page"><div className="feature-hero"><span className="eyebrow">JYC RECRUITMENT</span><h1>Find a team to build with.</h1><p>Recruitment appears only when a club chooses to open it. Explore official club information before applying.</p></div>{clubs.length?<div className="feature-grid">{clubs.map(c=><article className="feature-card" key={c.id}><span className="tag">{c.type} · {c.category||'Club'}</span><h3>{c.name}</h3><p>{c.recruitment.title||'Recruitment Open'}</p>{c.recruitment.deadline&&<small>Deadline · {fmtDate(c.recruitment.deadline)}</small>}<div className="feature-actions"><button onClick={()=>nav('/clubs/'+c.id)}>View club</button>{c.recruitment.link&&<a href={c.recruitment.link} target="_blank" rel="noreferrer">Apply ↗</a>}</div></article>)}</div>:<div className="feature-empty large"><strong>Recruitment will appear here.</strong><span>No published club has recruitment enabled right now.</span></div>}</section>}

export function AuditionsHub({data}){const nav=useNavigate();const clubs=publishedClubs(data).filter(c=>c.auditions?.on);return <section className="section page feature-page"><div className="feature-hero"><span className="eyebrow">JYC AUDITIONS</span><h1>Step onto the stage.</h1><p>Auditions are separate from recruitment and are shown only for clubs that publish an audition call.</p></div>{clubs.length?<div className="feature-grid">{clubs.map(c=><article className="feature-card" key={c.id}><span className="tag">{c.name}</span><h3>{c.auditions.title||'Auditions Open'}</h3><p>{c.description}</p>{c.auditions.deadline&&<small>Deadline · {fmtDate(c.auditions.deadline)}</small>}<div className="feature-actions"><button onClick={()=>nav('/clubs/'+c.id)}>View club</button>{c.auditions.link&&<a href={c.auditions.link} target="_blank" rel="noreferrer">Audition ↗</a>}</div></article>)}</div>:<div className="feature-empty large"><strong>No auditions published right now.</strong><span>Check back when a JYC club opens its audition window.</span></div>}</section>}

export function MyJYC({data}){const nav=useNavigate();const [tick,setTick]=useState(0);const savedClubIds=useMemo(()=>data.clubs.filter(c=>localStorage.getItem(savedKeys.club+c.id)==='1'),[data,tick]);const savedEventIds=useMemo(()=>data.events.filter(e=>localStorage.getItem(savedKeys.event+e.id)==='1'),[data,tick]);const unsave=(kind,id)=>{localStorage.removeItem((kind==='club'?savedKeys.club:savedKeys.event)+id);setTick(x=>x+1)};return <section className="section page feature-page"><div className="feature-hero"><span className="eyebrow">MY JYC</span><h1>Your saved campus experience.</h1><p>Saved clubs and events stay on this device. No account is required for favourites.</p></div><div className="saved-columns"><div><h3>Saved Clubs <span>{savedClubIds.length}</span></h3>{savedClubIds.length?savedClubIds.map(c=><div className="saved-row" key={c.id}><div><strong>{c.name}</strong><small>{c.category||c.type}</small></div><button onClick={()=>nav('/clubs/'+c.id)}>Open</button><button className="ghost" onClick={()=>unsave('club',c.id)}>Remove</button></div>):<div className="feature-empty"><span>Save a club from the Clubs page to see it here.</span></div>}</div><div><h3>Saved Events <span>{savedEventIds.length}</span></h3>{savedEventIds.length?savedEventIds.map(e=><div className="saved-row" key={e.id}><div><strong>{e.title}</strong><small>{fmtDate(e.date)} · {e.start||'TBA'}</small></div><button onClick={()=>nav('/events/'+e.id)}>Open</button><button className="ghost" onClick={()=>unsave('event',e.id)}>Remove</button></div>):<div className="feature-empty"><span>Save an event from Events to keep it handy.</span></div>}</div></div></section>}

export function CalendarPage({data}){const events=publishedEvents(data).sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`));const [month,setMonth]=useState(new Date());const y=month.getFullYear(),m=month.getMonth();const first=new Date(y,m,1).getDay();const days=new Date(y,m+1,0).getDate();const by=events.reduce((o,e)=>{o[e.date]??=[];o[e.date].push(e);return o},{});return <section className="section page feature-page"><div className="feature-hero"><span className="eyebrow">JYC CALENDAR</span><h1>Plan around what’s next.</h1><p>Published JYC events, with live and past states derived from their times.</p></div><div className="calendar-toolbar"><button onClick={()=>setMonth(new Date(y,m-1,1))}>←</button><strong>{month.toLocaleDateString('en-IN',{month:'long',year:'numeric'})}</strong><button onClick={()=>setMonth(new Date(y,m+1,1))}>→</button><button className="today-btn" onClick={()=>setMonth(new Date())}>Today</button></div><div className="month-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><b key={x}>{x}</b>)}{Array.from({length:first}).map((_,i)=><span className="empty-day" key={'e'+i}/>)}{Array.from({length:days},(_,i)=>i+1).map(day=>{const key=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;return <div className={`month-day ${by[key]?'has-events':''}`} key={key}><b>{day}</b>{(by[key]||[]).slice(0,3).map(e=><button key={e.id} onClick={()=>location.href='/events/'+e.id}>{e.title}</button>)}</div>})}</div></section>}

export function NotificationCenter({data}){const [permission,setPermission]=useState(()=>typeof Notification!=='undefined'?Notification.permission:'unsupported');const [items,setItems]=useState([]);useEffect(()=>{const arr=[];if(data.announcement?.on&&data.announcement.text)arr.push({id:'announcement',title:'JYC announcement',text:data.announcement.text,url:data.announcement.link||'/'});publishedEvents(data).filter(e=>eventState(e)==='upcoming').slice(0,5).forEach(e=>arr.push({id:e.id,title:e.title,text:`${fmtDate(e.date)} · ${e.start||'Time TBA'}`,url:'/events/'+e.id}));setItems(arr)},[data]);const enable=async()=>{if(!('Notification' in window)){setPermission('unsupported');return}const p=await Notification.requestPermission();setPermission(p)};return <section className="section page feature-page"><div className="feature-hero"><span className="eyebrow">NOTIFICATION CENTER</span><h1>Don’t miss the next JYC update.</h1><p>Browser permission controls local alerts. Full web push also requires the VAPID configuration and deployed notification function.</p><button className="btn" onClick={enable}>{permission==='granted'?'Notifications enabled':'Enable browser notifications'}</button></div><div className="notification-list">{items.length?items.map(n=><a key={n.id} href={n.url}><span>JYC</span><div><strong>{n.title}</strong><small>{n.text}</small></div>↗</a>):<div className="feature-empty"><span>No notifications yet.</span></div>}</div></section>}

export function ReminderButton({event}){const key=`jyc-reminder-${event.id}`;const [on,setOn]=useState(()=>localStorage.getItem(key)==='1');const toggle=async e=>{e.stopPropagation();if(!on&&'Notification' in window){const p=Notification.permission==='default'?await Notification.requestPermission():Notification.permission;if(p!=='granted')return}const next=!on;setOn(next);if(next){localStorage.setItem(key,'1');localStorage.setItem(key+'-at',new Date(`${event.date}T${event.start||'09:00'}`).getTime()-86400000)}else{localStorage.removeItem(key);localStorage.removeItem(key+'-at')}};return <button className={`save-btn ${on?'saved':''}`} onClick={toggle}>{on?'Reminder set':'Remind me'}</button>}

export function EventTools({event}){const [copied,setCopied]=useState(false);const url=window.location.href;const copy=async()=>{try{await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{window.prompt('Copy event link:',url)}};const share=async()=>{if(navigator.share){await navigator.share({title:event.title,text:`${event.title} · JYC`,url});}else await copy()};const qr=`https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(url)}`;return <div className="event-tools"><button onClick={share}>Share ↗</button><button onClick={copy}>{copied?'Copied':'Copy link'}</button><details><summary>QR code</summary><img src={qr} alt="QR code for this event"/><small>Scan to open this event page.</small></details></div>}

export function DownloadICS({event}){const toUTC=(date,time)=>{const d=new Date(`${date}T${time||'00:00'}:00`);return d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z')};const download=()=>{const start=toUTC(event.date,event.start);const end=toUTC(event.date,event.end||event.start||'23:59');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//JYC//EN','BEGIN:VEVENT',`UID:${event.id}@jyc128`, `DTSTAMP:${toUTC(new Date().toISOString().slice(0,10),'00:00')}`,`DTSTART:${start}`,`DTEND:${end}`,`SUMMARY:${String(event.title||'JYC Event').replace(/\n/g,' ')}`,`LOCATION:${String(event.venue||'').replace(/\n/g,' ')}`,`DESCRIPTION:${String(event.description||'').replace(/\n/g,' ')}`,'END:VEVENT','END:VCALENDAR'];const blob=new Blob([lines.join('\r\n')],{type:'text/calendar;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${slug(event.title)||'jyc-event'}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};return <button className="btn secondary" onClick={download}>Download .ics</button>}

export function RegistrationPage({data,id}){const event=data.events.find(e=>e.id===id||slug(e.title)===slug(id));const [form,setForm]=useState({name:'',email:'',enrollment_no:'',phone:'',year:'',branch:''});const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);if(!event||!event.published||event.archived)return <section className="section page"><div className="feature-empty large"><strong>Registration is unavailable.</strong><span>This event is not currently accepting registrations.</span></div></section>;const open=!event.registrationDeadline||new Date(event.registrationDeadline)>new Date();if(event.registrationMode!=='native')return <section className="section page feature-page"><div className="feature-hero"><span className="eyebrow">EVENT REGISTRATION</span><h1>{event.title}</h1><p>This event uses an external registration form.</p><a className="btn" href={event.registrationUrl||'/events/'+event.id} target={event.registrationUrl?'_blank':undefined} rel={event.registrationUrl?'noreferrer':undefined}>{event.registrationUrl?'Open registration ↗':'Back to event'}</a></div></section>;const submit=async e=>{e.preventDefault();if(!open)return;setBusy(true);setStatus('');try{const {error}=await (await import('./lib/supabase')).supabase.from('jyc_event_registrations').insert({...form,event_id:event.id});if(error)throw error;setStatus('Registration submitted successfully.');setForm({name:'',email:'',enrollment_no:'',phone:'',year:'',branch:''})}catch(err){setStatus(err.code==='23505'?'This email is already registered for this event.':err.message||'Could not submit registration.')}finally{setBusy(false)}};return <section className="section page feature-page"><div className="feature-hero"><span className="eyebrow">REGISTER NOW</span><h1>{event.title}</h1><p>{open?'Complete the official JYC registration form below.':'Registrations are closed.'}</p></div>{open?<form className="native-registration" onSubmit={submit}><div className="form-grid"><input required placeholder="Full name *" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" placeholder="Email *" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Enrollment number" value={form.enrollment_no} onChange={e=>setForm({...form,enrollment_no:e.target.value})}/><input placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="Year" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/><input placeholder="Branch" value={form.branch} onChange={e=>setForm({...form,branch:e.target.value})}/></div>{status&&<div className="success-box">{status}</div>}<button className="btn" disabled={busy}>{busy?'Submitting…':'Submit registration'}</button></form>:<div className="feature-empty"><strong>Registrations closed.</strong><span>The deadline for this event has passed.</span></div>}</section>}

export function JsonLd({data}){useEffect(()=>{const id='jyc-jsonld';let el=document.getElementById(id);if(!el){el=document.createElement('script');el.id=id;el.type='application/ld+json';document.head.appendChild(el)}el.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Organization','name':'JIIT Youth Club','alternateName':'JYC','url':window.location.origin,'sameAs':['https://www.instagram.com/jiityouthclub128/']})},[data]);return null}

export function ErrorBoundary({children}){const [failed,setFailed]=useState(false);if(failed)return <section className="section page"><div className="feature-empty large"><strong>Something went wrong.</strong><span>The page hit an unexpected error. Reload to continue.</span><button className="btn" onClick={()=>location.reload()}>Reload</button></div></section>;return <Boundary setFailed={setFailed}>{children}</Boundary>}
class Boundary extends React.Component{constructor(p){super(p);this.state={error:false}}static getDerivedStateFromError(){return {error:true}}componentDidCatch(error,info){try{localStorage.setItem('jyc-last-error',JSON.stringify({message:error.message,stack:error.stack,componentStack:info.componentStack,time:new Date().toISOString()}))}catch{}this.props.setFailed(true)}render(){return this.state.error?null:this.props.children}}
