import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createPortal} from 'react-dom';
import {BrowserRouter,Navigate,useLocation,useNavigate} from 'react-router-dom';
import {supabase} from './lib/supabase';
import {jycToast} from './lib/ui';
import './v23.6-consolidated.css';
import './jyc-editorial-centered.css';
import './v26-beige-signature.css';
import './v28-editorial-system.css';
import './v29-interaction-polish.css';
import './v32-public-production-overhaul.css';
import './v33-final-public-experience.css';
import './v36-depth-polish.css';
import './jyc-logo-theme.css';
import {JYC_HUB_CONTENT, JYC_HUB_FAMILIES, hubProfile} from './v21-hub-content.js';
import {JYC_ORIENTATION_FAMILIES,JYC_ORIENTATION_LAYERS,JYC_ORIENTATION_EVENTS,JYC_ORIENTATION_AT_A_GLANCE} from './jyc-orientation-insights.js';
import {hubDetails} from './v23.6-hub-details.js';
import {hubIdentity,eventIdentity} from './hub-identities.js';
import {PDF_HUB_GALLERY,PDF_HUB_STORIES,HUB_PHOTO_MAP} from './pdf-hub-content.js';
import {PDF_HUB_EXTRA_GALLERY,PDF_HUB_PROGRAMME} from './pdf-hub-extra.js';
import {enrichSourceClubs,mergeSourceGallery,sourceHubMedia} from './jyc-source-media.js';
import {JYC_EVENT_CATEGORIES,JYC_COMMUNITY_DISCOVERY,JYC_PUBLIC_ACTIVITIES} from './public-v1/config.js';
import {JYC_SOCIALS,festSocialProfile,socialProfile} from './jyc-socials.js';
